# Generated by Django 4.0.4 on 2022-05-27 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Playlist',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('playlist_name', models.CharField(max_length=254)),
                ('videos', models.JSONField(default=dict)),
                ('username', models.CharField(max_length=254)),
            ],
        ),
    ]
